-- SEQUENCE vs IDENTITY
-- sequence
create sequence cus_id_s
    minvalue 1
    maxvalue 9999
    start with 1
    increment by 1
    nocache;

select cus_id_s.nextval from dual;
select sequence_name, min_value,max_value,increment_by,last_number from user_sequences;

create table cust_one(
cust_id number default cus_id_s.nextval,
cust_name varchar2(40)
);

alter table cust_one add constraint cust_one_pk primary key (cust_id);

insert into cust_one (cust_name) values('Asim ali');

select cus_id_s.currval from dual;
select * from cust_one;

select * from user_sequences;
select * from user_tab_cols where identity_column = 'YES';

-- IDENTITY COLUMN
--GENERATED [ ALWAYS | BY DEFAULT [ ON NULL ] ] AS IDENTITY [ ( identity_options ) ]

--Using ALWAYS forces the use of the identity. If an insert statement references the identity column, even to specify a NULL value, an error is produced.
create table cust_two(
cust_id number GENERATED ALWAYS AS IDENTITY,
description varchar2(100)
);

insert into cust_two (description) values('just Description'); -- 1 row created
insert into cust_two (cust_id, description) values(null, 'cust_id=NULL and Description'); -- SQL Error: ORA-32795: cannot insert into a generated always identity column
insert into cust_two (cust_id, description) values(999, 'cust_id=999 and Description'); -- SQL Error: ORA-32795: cannot insert into a generated always identity column

--Using BY DEFAULT allows you to use the identity if the column isn't referenced in the insert statement, but if the column is referenced, the specified value will be used in place of the identity. Attempting to specify the value NULL in this case results in an error, since identity columns are always NOT NULL.
DROP TABLE cust_two PURGE;
create table cust_two (
id number GENERATED BY DEFAULT AS IDENTITY,
description varchar2(100)
);

insert into cust_two (description) values('just Description'); -- 1 row inserted
insert into cust_two (id,description) values(999,'id=999 and Description'); -- 1 row inserted
insert into cust_two (id,description) values(null,'id=NULL and Description'); -- SQL Error: ORA-01400: cannot insert NULL into ("MUSTAN_"."CUST_TWO"."ID")

--Using BY DEFAULT ON NULL allows the identity to be used if the identity column is referenced, but a value of NULL is specified.
DROP TABLE cust_two PURGE;
create table cust_two (
id number GENERATED BY DEFAULT ON NULL AS IDENTITY primary key,
description varchar2(100)
);

insert into cust_two (description) values('just Description'); -- 1 row inserted
insert into cust_two (id,description) values(999,'id=999 and Description'); -- 1 row inserted
insert into cust_two (id,description) values(null,'id=NULL and Description'); -- 1 row inserted
commit;
select * from cust_one;
select * from cust_two;
desc cust_two;

SELECT object_name, object_type
FROM   user_objects where object_type = 'SEQUENCE'; -- ISEQ$$_115016 object_name for ID of cust_two table
select * from user_tab_cols where identity_column = 'YES'; 

-- Find details of sequence of identity columns
select uic.table_name, uic.column_name, us.*
from user_tab_identity_cols uic, user_sequences us
where uic.sequence_name = us.sequence_name;

select * from user_tab_identity_cols;
select * from user_sequences;

select ISEQ$$_115016.currval from dual;

select *
from user_objects where object_name = 'ISEQ$$_115016';

select *
from user_objects where object_id = 115016;
